- hosts: olvm
  become: yes
  become_method: sudo
  gather_facts: false
  vars_files:
    - password.yml
  collections:
    - ovrit.ovrit
    - ansible.posix
  tasks:

    - name: Login to OLVM manager
      ovirt_auth:
        hostname: "{{ olvm_fqdn }}"
        username: "{{ olvm_user }}"
        password: "{{ olvm_password }}"
        ca_file: "{{ olvm_cafile | default(omit) }}"
        insecure: "{{ olvm_insecure | default(true) }}"
      tags:
        - always
    - name: Check VM status
      
